#服务名
spring:
  application:
    name: dosimple-gateway
  cloud:
    gateway:
      routes:
        - id:  SEARCH-USER
        # lb代表从注册中心获取服务
          uri: lb://DOSIMPLE-BIZ-USER
          predicates:
          # 转发该路径！,/dosimple_biz_user/**,
          - Path=/dosimple_biz_user/**
          #加上StripPrefix=1，服务时会去掉dosimple_biz_user，只保留**部分
          filters:
            - StripPrefix=1
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@addressKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
  redis:
    port: 6379
    timeout: 6000
    host: localhost
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 20
        min-idle: 0
        max-wait: -1